Update electron-builder to 17.2.0
Some package.json options are no longer valid with current electron-builder so I removed them. Might have to look into if they just got replaced or are just no longer needed.

Error: Config is invalid:
{
  "homepage": "Unknown option",
  "category": "Unknown option",
  "linux": [
    {
      "arch": "Unknown option"
    },
    "Invalid option object"
  ]
}